### ISSUE TITLE
Unable to find or load main class

### ISSUE THREAD

**Issue by princejha95** [bohdan-leonchyk/swaggergenerator#1]
Hi, I have cloned your repo and tried to compile AppRunner.java but it is giving following error:
**Error: Could not find or load main class AppRunner.java**

Could you please tell me why is it happening ?

I am using mac OSX

**Comment by bohdan-leonchyk** [comment]
Hi @princejha95 ,
1. Do "git clone" of this project
2. Import this project as "Maven project" to your IDE (Eclipse or IntellijIDEA)
3. Do "maven clean" and "maven install"
4. In your IDE run AppRunner.java as Java Application
